### ISSUE TITLE
C86申込

### ISSUE THREAD

**Issue by kubosho** [fruitsnoodle/comic#3]
そもそも申込するのか、どこかに委託するのか

申込する場合は、
- 申込開始: 2014/1/28(火) 13:00
- 決済締切: 2014/2/12(水) 23:59
- 申込締切: 2014/2/18(火) 23:59

というスケジュールなので、余裕を見て、2014/2/7(金)には全ての手続きが終わっているように。
- 申し込み担当：kubosho？krafatos？
- サークル名：
- ほか項目：

※申請したことないので、記入/検討必要な項目がありましたらこちらに書いていただければ助かります！（キンキン）

**Comment by fruitsnoodle** [comment]
最初の想定はくぼしょーの技術本のおまけ程度だったので、急にみんなを巻き込んだのでどうしようかをいま考えております(;′Д`)ノ

**Comment by kubosho** [comment]
この規模になったら別で出したほうがいい気がしてるー

**Comment by fruitsnoodle** [comment]
そう思っております！
もし委託でしたらくぼしょーのところは無理かな？

**Comment by kubosho** [comment]
委託は問題ないです

**Comment by fruitsnoodle** [comment]
ではぜひお願いいたします！！！！！！

**Comment by krfatos** [comment]
去年の申し込み落ちたんやけど今年はあたり安くなるかも？
こちらから申し込んでもいいんですよーw

**Comment by kubosho** [comment]
そうなると、krfatosさんのほうで申し込んだほうがいいかもしれないですねー

**Comment by fruitsnoodle** [comment]
ではくらら氏お願いしますーー！

**Comment by krfatos** [comment]
ほむほむではサークル名とかアイディアがありましたら宜しくお願い致しますー
WEBで申し込みますー

**Comment by krfatos** [comment]
あとは落ちる確率の低い大阪インテックスの方はいかがでしょうかー？

**Comment by fruitsnoodle** [comment]
個人的には参加さえできれば特にこだわりがないですー

**Comment by krfatos** [comment]
では「進捗ホイホイ」って宜しいでしょうか？
